//! Bootstrap icon helpers.
//!
//! The functions generated by `iced_fonts` use `Shaping::Basic`, which
//! cannot shape the Private Use Area codepoints that icon fonts live in, so
//! the glyphs silently fail to render. These wrappers re-apply advanced
//! shaping, so always use them instead of `iced_fonts::bootstrap` directly.

use iced::widget::Text;
use iced::widget::text::Shaping;
use iced_fonts::bootstrap;

macro_rules! icons {
    ($($name:ident),* $(,)?) => {
        $(
            pub fn $name<'a>() -> Text<'a> {
                bootstrap::$name().shaping(Shaping::Advanced)
            }
        )*
    };
}

icons!(
    arrow_repeat,
    aspect_ratio,
    check_lg,
    chevron_left,
    chevron_right,
    clipboard,
    file_earmark,
    folder,
    hdd,
    image,
    images,
    info_circle,
    pause_fill,
    pencil_square,
    play_fill,
    question_circle,
    trash,
    volume_mute,
    volume_up,
    x_lg,
    zoom_in,
);

#[cfg(test)]
mod tests {
    #[test]
    fn every_icon_helper_builds() {
        for icon in [
            super::arrow_repeat(),
            super::aspect_ratio(),
            super::check_lg(),
            super::chevron_left(),
            super::chevron_right(),
            super::clipboard(),
            super::file_earmark(),
            super::folder(),
            super::hdd(),
            super::image(),
            super::images(),
            super::info_circle(),
            super::pause_fill(),
            super::pencil_square(),
            super::play_fill(),
            super::question_circle(),
            super::trash(),
            super::volume_mute(),
            super::volume_up(),
            super::x_lg(),
            super::zoom_in(),
        ] {
            let _ = icon.size(16);
        }
    }
}
