//! Bootstrap icon helpers.
//!
//! The functions generated by `iced_fonts` use `Shaping::Basic`, which
//! cannot shape the Private Use Area codepoints that icon fonts live in, so
//! the glyphs silently fail to render. These wrappers re-apply advanced
//! shaping, so always use them instead of `iced_fonts::bootstrap` directly.

use iced::widget::Text;
use iced::widget::text::Shaping;
use iced_fonts::bootstrap;

macro_rules! icons {
    ($($name:ident),* $(,)?) => {
        $(
            pub fn $name<'a>() -> Text<'a> {
                bootstrap::$name().shaping(Shaping::Advanced)
            }
        )*
    };
}

icons!(
    aspect_ratio,
    check_lg,
    clipboard,
    file_earmark,
    folder,
    hdd,
    image,
    images,
    info_circle,
    zoom_in,
);
